version: 1
disable_existing_loggers: true
formatters:
  standard:
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: '[%(asctime)s] %(levelname)-7s | %(message)s'
  simple:
    datefmt: '%H:%M:%S'
    format: '[%(asctime)s] %(name)-7s | %(levelname)-7s | %(message)s'
handlers:
  common_log:
    level: DEBUG
    formatter: standard
    class: logging.handlers.TimedRotatingFileHandler
    filename: '~/.twnews/log/common.log'
    when: 'D'
  news_log:
    level: DEBUG
    formatter: standard
    class: logging.handlers.TimedRotatingFileHandler
    filename: '~/.twnews/log/news.log'
    when: 'D'
  finance_log:
    level: DEBUG
    formatter: standard
    class: logging.handlers.TimedRotatingFileHandler
    filename: '~/.twnews/log/finance.log'
    when: 'D'
  stdout:
    level: DEBUG
    formatter: simple
    class: logging.StreamHandler
    stream: ext://sys.stdout
  telegram:
    level: INFO
    formatter: simple
    class: busm.BusmHandler
    subject: finance crawler
loggers:
  common:
    level: DEBUG
    handlers:
      - common_log
      - stdout
  news:
    level: DEBUG
    handlers:
      - news_log
      - stdout
  finance:
    level: DEBUG
    handlers:
      - finance_log
      - telegram
      - stdout
