version: 1
disable_existing_loggers: true
formatters:
  standard:
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: '[%(asctime)s] %(name)-7s | %(levelname)-7s | %(message)s'
  simple:
    datefmt: '%H:%M:%S'
    format: '[%(asctime)s] %(levelname)-7s | %(message)s'
handlers:
  none:
    level: CRITICAL
    class: logging.NullHandler
  stdout:
    level: INFO
    formatter: simple
    class: logging.StreamHandler
    stream: ext://sys.stdout
  news_log:
    level: INFO
    formatter: standard
    class: logging.handlers.TimedRotatingFileHandler
    filename: '~/.twnews/log/news.log'
    when: 'D'
  finance_log:
    level: INFO
    formatter: standard
    class: logging.handlers.TimedRotatingFileHandler
    filename: '~/.twnews/log/finance.log'
    when: 'D'
  telegram:
    level: INFO
    formatter: simple
    class: busm.BusmHandler
loggers:
  news:
    level: DEBUG
    handlers:
      - news_log
      - telegram
      - stdout
    propagate: true
  finance:
    level: DEBUG
    handlers:
      - finance_log
      - telegram
      - stdout
    propagate: true
